=== TheArchitectit/pi-mega-compact/conformance/vector-cortex/v2/schemas/minhash-seeds.schema.json
{"$schema":"https://json-schema.org/draft-07/schema#","description":"The published 256 unsigned (a,b) seed pairs + p for the frozen MinHashV2 scheme. Values exceed 2^53 so a/b/p are DECIMAL STRINGS for exactness.","properties":{"bands":{"type":"integer"},"count":{"type":"integer"},"p":{"type":"string"},"schema":{"type":"string"},"seedPairs":{"items":{"properties":{"a":{"type":"string"},"b":{"type":"string"}},"required":["a","b"],"type":"object"},"type":"array"},"shingleCodePoints":{"type":"integer"},"signatureBytes":{"type":"integer"},"valuesPerBand":{"type":"integer"}},"required":["schema","p","count","shingleCodePoints","signatureBytes","bands","valuesPerBand","seedPairs"],"title":"MinHashV2 frozen seed table","type":"object"}

=== TheArchitectit/pi-mega-compact/conformance/vector-cortex/v2/minhash/seeds-v2.json
{"bands":64,"count":256,"p":"2305843009213693951","schema":"schemas/minhash-seeds.schema.json","seedPairs":[{"a":"335969604426165204","b":"382143801352175574"},{"a":"802549505401733919","b":"1091462944885681402"},{"a":"480044661532155463","b":"974077268627436132"},{"a":"379593566942188319","b":"1083127051842233090"},{"a":"1985213944130836756","b":"823071497570998414"},{"a":"1397099859018412949","b":"1675906219990768070"},{"a":"677467483898877670","b":"660689412679503122"},{"a":"1768098721344731938","b":"1500021190622841984"},{"a":"602877630283250289","b":"1557681743127533488"},{"a":"2117581838258622523","b":"469497783332174430"},{"a":"529935114200596404","b":"920185578024695915"},{"a":"494021942876223261","b":"1061075851527728994"},{"a":"2199132240253924208","b":"204922499205046077"},{"a":"364596607476790996","b":"686676749687249468"},{"a":"543291530920862944","b":"489540780730436231"},{"a":"1332144740538585787","b":"1356138603772775747"},{"a":"1464522274843824031","b":"238799029585149641"},{"a":"2208609429079792565","b":"1003285976717489791"},{"a":"1018387934614936793","b":"749563371834975064"},{"a":"2254232437006061633","b":"1824185571130013569"},{"a":"1346048314985942503","b":"1775144145205173475"},{"a":"60479027462535371","b":"9298906734714608"},{"a":"955422019825599564","b":"338124926916911045"},{"a":"541375215668408450","b":"1192182016329430185"},{"a":"1881713840679801590","b":"322429120178345403"},{"a":"1854093359398082969","b":"2103879416401043062"},{"a":"1828429920900110423","b":"1178190879162993747"},{"a":"1450921093397075430","b":"242315821820930777"},{"a":"1787044100439373763","b":"2057787178714282004"},{"a":"453209070326122417","b":"50252394291866651"},{"a":"1661906911561445876","b":"575020675036440455"},{"a":"584819717070514798","b":"1891304907505495240"},{"a":"822881252180099196","b":"1931335105259420820"},{"a":"1595386056261470383","b":"345601500866488826"},{"a":"546222515087468387","b":"351430209898521037"},{"a":"90547148208673777","b":"1060351254881038720"},{"a":"1111102750118495403","b":"1244482540302540888"},{"a":"2143223582979668260","b":"1447396109632162160"},{"a":"2125738563839260937","b":"719053843555250793"},{"a":"1096100720573747133","b":"492491297468983073"},{"a":"2009001193115220257","b":"1352285358962633631"},{"a":"1540074141406283608","b":"973008513335333097"},{"a":"1727392125194459905","b":"1706545984236855971"},{"a":"448005709200682438","b":"302013221607001097"},{"a":"229164324405628606","b":"1866267639199478231"},{"a":"1035333618295496139","b":"102567391888261104"},{"a":"1825935373043186420","b":"298151788370363536"},{"a":"651757159401165545","b":"933882705162541412"},{"a":"757971495482949368","b":"309748120623906392"},{"a":"1716326362471456386","b":"230894888423969579"},{"a":"1387551383409474156","b":"2119136773341165471"},{"a":"967540496314961866","b":"2099096594312938033"},{"a":"892315333766079487","b":"2134705025042866793"},{"a":"1359867774990232205","b":"1009754356691905287"},{"a":"167087364825411634","b":"775906659053829999"},{"a":"1734500172778751580","b":"235728562303441190"},{"a":"195876846073152959","b":"1054879074261812962"},{"a":"1306808337100047438","b":"2191442050987328578"},{"a":"1760257408674517842","b":"1770361746616741761"},{"a":"389070330344339617","b":"1463859203634503520"},{"a":"2202569378033746350","b":"467294984093412296"},{"a":"2218963526517448767","b":"1640381158024236095"},{"a":"337794431190954842","b":"2077755448439448741"},{"a":"906979417347948161","b":"737609049083222653"},{"a":"220523326229170348","b":"953687689295362176"},{"a":"1681230596763529608","b":"95798550237482550"},{"a":"2100514604078916215","b":"148682677297820308"},{"a":"124884749525263470","b":"1112051205788473032"},{"a":"2209283161193796041","b":"89091007000639195"},{"a":"55998708992889736","b":"412901333540774036"},{"a":"1953752088868979517","b":"1777598707398018023"},{"a":"1251978892502800616","b":"353607048245699431"},{"a":"2012740611954472813","b":"1063158263146995400"},{"a":"131331621933991693","b":"700578609411273879"},{"a":"1313047283506449607","b":"2108049448890958066"},{"a":"1941084371911880152","b":"2020434912183271331"},{"a":"2300535320503891933","b":"2153047288260645324"},{"a":"1214847655028735456","b":"382201717938447530"},{"a":"1266593045732271012","b":"1321795973515183565"},{"a":"1395965576859536417","b":"1284460655645973667"},{"a":"744617039190441341","b":"1068301896892063851"},{"a":"1347161655626634131","b":"567286565394605473"},{"a":"182067471306154652","b":"915102693136929578"},{"a":"116487390399764987","b":"774094202509143020"},{"a":"718564291710715804","b":"1007949785400943227"},{"a":"1873637944865084535","b":"1495073235783866156"},{"a":"1055780799340587345","b":"1410106958616938307"},{"a":"284221060096550567","b":"1646963497863389079"},{"a":"661995321692844721","b":"155148966286549214"},{"a":"393392971947405460","b":"1514883147837560513"},{"a":"1979406771391166808","b":"907840338192869086"},{"a":"804816523319318429","b":"1808061608400262286"},{"a":"349498730683151412","b":"1905474312303063123"},{"a":"1834539727382175085","b":"216125898595400353"},{"a":"1406742645002745174","b":"1653957126484151046"},{"a":"842121297450531392","b":"981526853026775992"},{"a":"1742861406026922204","b":"415256865353577007"},{"a":"610396011366832923","b":"1292632953791166246"},{"a":"910959402289237718","b":"1284716905304660119"},{"a":"487339728017282054","b":"1553959156298208532"},{"a":"1319497328415240055","b":"140961390774969221"},{"a":"540669270590141233","b":"1140128036034984350"},{"a":"985578674954812470","b":"567830027968235159"},{"a":"2292280183433815666","b":"896103670890608057"},{"a":"1459297041679660543","b":"1467788224508650398"},{"a":"354395637893353530","b":"1640348147464489557"},{"a":"2022959496258778010","b":"1622224509215640149"},{"a":"358139990386807124","b":"1806799213115655333"},{"a":"453572761629709153","b":"1615378104673032303"},{"a":"361211885756735080","b":"1008532039863482281"},{"a":"943253185979398396","b":"1468671949526089361"},{"a":"1745978524400371110","b":"1396677374940974484"},{"a":"409258719394864938","b":"2074677319175792008"},{"a":"1581548109081347071","b":"2123231979798580633"},{"a":"1946223253199428791","b":"1390746059413906762"},{"a":"96846486876033131","b":"842303677969452915"},{"a":"187482228824660857","b":"519366504080694422"},{"a":"799692270822882109","b":"1486056671090673772"},{"a":"272489025069889308","b":"667700530554737166"},{"a":"604656804834291475","b":"282161026586340787"},{"a":"2124513398218293487","b":"998975078567212732"},{"a":"2178457357017334007","b":"163946328135100367"},{"a":"470383776259480918","b":"719755256623638824"},{"a":"1619455066941225062","b":"286676353106102755"},{"a":"2040788235717217159","b":"1173903822199968441"},{"a":"664829034763306232","b":"141736419421291194"},{"a":"120785028271168688","b":"1383040116766675571"},{"a":"1722530563607722200","b":"1024963872537807398"},{"a":"1792917328072960430","b":"620844077829154946"},{"a":"683819322753267812","b":"2292511154556887667"},{"a":"1174693230024461548","b":"82037344001621955"},{"a":"1730495773213370382","b":"1589862023362447561"},{"a":"1465032383046864277","b":"1110267765735215933"},{"a":"984879523777735603","b":"1254272108959311759"},{"a":"2021912946896336805","b":"1811150427499650144"},{"a":"1768214442504913822","b":"1474775227374408427"},{"a":"417742783972644230","b":"1898101088094716669"},{"a":"1057023069133967239","b":"1569472379313128665"},{"a":"476751784093085703","b":"90488353298087227"},{"a":"1987270000860780566","b":"1903409009381373640"},{"a":"182462930527460300","b":"1155474464957733297"},{"a":"321448575993805928","b":"2179274749796571231"},{"a":"748699555303540217","b":"2236520960425945032"},{"a":"194914748143566710","b":"2076293154200721402"},{"a":"367980405402013746","b":"39247507422728137"},{"a":"616718454662134264","b":"861706965043266626"},{"a":"1961687985113766467","b":"2005535214609074419"},{"a":"1986963917570780637","b":"1994799413577757883"},{"a":"1269679219093585763","b":"2142761656268351027"},{"a":"374936842557053734","b":"1874173233593414855"},{"a":"1212842758974975204","b":"908612355786956261"},{"a":"725409551904790756","b":"690520219600997032"},{"a":"1795865006898650917","b":"2211884419380557163"},{"a":"1595791036742675506","b":"1864602364191586210"},{"a":"2238939373936566262","b":"36848632161201104"},{"a":"479522217088376823","b":"314021319627509985"},{"a":"513764833170675716","b":"1799052803419499557"},{"a":"1178964275227720577","b":"977021420939615457"},{"a":"1574442753233239802","b":"1803351572794555099"},{"a":"154822810933885514","b":"912952328820866914"},{"a":"1630266220173214611","b":"116085302329807028"},{"a":"1256839723569398874","b":"810126420417572624"},{"a":"323790622554066405","b":"1281542523263004517"},{"a":"1333579260936075152","b":"1691984557715777735"},{"a":"796353657519982891","b":"831538783605154200"},{"a":"2260543659659481672","b":"1134320361675014086"},{"a":"1137797518347821650","b":"1928873175206477025"},{"a":"1128111184525251373","b":"132955700841915946"},{"a":"2128564081025075971","b":"864199658269201792"},{"a":"1203183692412697564","b":"593127347190670611"},{"a":"1944214808771636121","b":"1400575642390090507"},{"a":"150430506297184340","b":"815455185756526722"},{"a":"75055280507129454","b":"1685162723900448485"},{"a":"563051381570862268","b":"2104305277560463231"},{"a":"536210057469920351","b":"495371906152612205"},{"a":"1001384296905343389","b":"286259105944304720"},{"a":"852984257342718491","b":"1090649075091830627"},{"a":"1063993463365980792","b":"70097816105289278"},{"a":"1997959707473589338","b":"1257069266999602990"},{"a":"669868926985577033","b":"312458931703007667"},{"a":"2030935009794037401","b":"1101148586079626735"},{"a":"2012890180830942504","b":"1446097123336914042"},{"a":"655178720272343395","b":"292111982580851379"},{"a":"1863997618640316953","b":"209141792859142453"},{"a":"1181225747644812637","b":"1621248133325691078"},{"a":"1167279193952696154","b":"1364207641016890961"},{"a":"737466174767671481","b":"71
